[config]
# If set to enabled, it will check for updates when you run the matugen command, notifying you that an update is avaiable.
# WARNING: Matugen needs to be compiled with the `update-informer` feature for this to work.
version_check = false

# The color which should be used as the source_color if no good color was found from an image.
# Can be defined in any css format.
# The cli flag will override this if used.
fallback_color = "#ffbf9b"

# Enables caching which will cache the colorscheme, custom colors, etc. into a cache folder located in
# Windows: C:\Users\user\AppData\Roaming\InioX\matugen\cache\images\<file>
# Linux: $XDG_CACHE_HOME/matugen/<file> or $HOME/.cache/matugen/images/<file>
# MacOS: $HOME/Library/Caches/matugen/images/<file>
# The file follows this naming: <image_name>.<image_extension>.<image_hash>.json
# For example: testimage.png.0cfd2d624b3d09bf6246b7be9ca79e207e7aa1189d961d44949628b99811bb9d.json
# You can modify the cache and it will then be loaded when using the same image.
# The colors are defined using the #RRGGBBAA format.
caching = false

# Changing the syntax
# Expr is for keywords like {{ <keyword> }}
expr_prefix = "{{"
expr_postfix = "}}"

# Block is for stuff like for loops etc.
block_prefix = "<*"
block_postfix = "*>"

# [config.wallpaper]
# Whether to set the wallpaper or not
# set = true

# The base command to run for applying the wallpaper, shouldn't have spaces in it.
# command = "swww"

# The arguments that will be provided to the command.
# Keywords like {{ mode }} or anything that works inside of hooks doesn't work here.
# The last argument will be the image path.
arguments = ["img", "--transition-type", "center"]

# For example, killing the wallpaper daemon. Usage is like a normal hook.
# pre_hook = ""

# [templates.includeme]
# input_path = "include.txt"
# The output path is optional if you just want to import the template anyways,
# output_path = "./a/include.txt"


[templates.sway]
input_path = '~/.config/matugen/templates/sway'
output_path = '~/.config/sway/colors.conf'
post_hook = 'swaymsg reload'


[templates.foot]
input_path = '~/.config/matugen/templates/foot.ini'
output_path = '~/.config/foot/colors.ini'


[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
